sessions:
- name: SYSTEM
  autostart: true
  windows:
  - name: footserver
    command: foot -s
  - name: megacmd
    command: mega-cmd
  - name: syteminfo
    command: btop
- name: MUSIC
  autostart: true
  windows:
  - name: cmus
    command: cmus
- name: DEFAULT
  autostart: true
  windows:
  - name: shell
    command: bash
- name: JUPYTER
  autostart: false
  windows:
  - name: lab
    command: snekai.sh lab
- name: LLM
  autostart: false
  windows:
  - name: openwebui
    command: openwebui-launcher.sh init
