
# Tmux Sessions Configuration
sessions:
  - name: MEGA
    autostart: true
    windows:
      - name: megacmd
        command: mega-cmd
  
  - name: MUSIC
    autostart: true
    windows:
      - name: cmus
        command: cmus
