sessions:
- name: SYSTEM
  autostart: true
  windows:
  - name: megacmd
    command: mega-cmd
  - name: syteminfo
    command: btop
- name: MUSIC
  autostart: true
  windows:
  - name: cmus
    command: cmus
- name: DEFAULT
  autostart: true
  windows:
  - name: shell
    command: bash
- name: OLLAMA
  autostart: false
  windows:
  - name: ollama
    command: ollama serve
- name: JUPYTER
  autostart: false
  windows:
  - name: lab
    command: snekai.sh lab
- name: SSH
  autostart: true
  windows:
  - name: ssh_fzf
    command: ssh-fzf.sh
